kunst_cafe_main_kunstcafe_main_artist_image_crud:
    resource: "@KunstCafeMainBundle/Resources/config/routing/artistimage.yml"
    prefix:   /admin/artist/image

kunst_cafe_main_kunstcafe_main_artist_crud:
    resource: "@KunstCafeMainBundle/Resources/config/routing/artist.yml"
    prefix:   /admin/artist

kunst_cafe_main_kunstcafe_main_calendar_crud:
    resource: "@KunstCafeMainBundle/Resources/config/routing/event.yml"
    prefix:   /admin/calendar

kunst_cafe_main_homepage:
    path:     /
    defaults: { _controller: KunstCafeMainBundle:Default:index }

kunst_cafe_main_about_us:
    path:     /about
    defaults: { _controller: KunstCafeMainBundle:Default:about }

kunst_cafe_main_calendar:
    path:     /calendar
    defaults: { _controller: KunstCafeMainBundle:Default:calendar }

kunst_cafe_main_artists:
    path:     /artists
    defaults: { _controller: KunstCafeMainBundle:Default:artists }

kunst_cafe_main_view_artist:
    path:     /artists/{slug}/view
    defaults: { _controller: KunstCafeMainBundle:Default:viewArtist }

# Admin

kunst_cafe_admin_homepage:
    path:     /admin
    defaults: { _controller: KunstCafeMainBundle:Admin:index }