kunstcafe_main_calendar_crud:
    path:     /
    defaults: { _controller: "KunstCafeMainBundle:Event:index" }

kunstcafe_main_calendar_crud_show:
    path:     /{id}/show
    defaults: { _controller: "KunstCafeMainBundle:Event:show" }

kunstcafe_main_calendar_crud_new:
    path:     /new
    defaults: { _controller: "KunstCafeMainBundle:Event:new" }

kunstcafe_main_calendar_crud_create:
    path:     /create
    defaults: { _controller: "KunstCafeMainBundle:Event:create" }
    requirements: { _method: post }

kunstcafe_main_calendar_crud_edit:
    path:     /{id}/edit
    defaults: { _controller: "KunstCafeMainBundle:Event:edit" }

kunstcafe_main_calendar_crud_update:
    path:     /{id}/update
    defaults: { _controller: "KunstCafeMainBundle:Event:update" }
    requirements: { _method: post|put }

kunstcafe_main_calendar_crud_delete:
    path:     /{id}/delete
    defaults: { _controller: "KunstCafeMainBundle:Event:delete" }
    requirements: { _method: post|delete }
